### ISSUE TITLE
When i do node bot.js this keeps coming up 

### ISSUE THREAD

**Issue by Rhino149** [VenkSociety/Tsuyo#24]
Error: Cannot find module '../build/better_sqlite3.node' 
and no matter what i do it continues to say that

**Comment by VenkSociety** [comment]
Did you type `npm install` before running the bot? This error shows that [better-sqlite3](https://www.npmjs.com/package/better-sqlite3) isn't installed.

**Comment by Rhino149** [comment]
yes i did several times and did node bot.js after each try

**Comment by VenkSociety** [comment]
Could you try running `npm install better-sqlite3` and post your error log? Your computer might have a problem with the installation.

**Comment by VenkSociety** [comment]
You could also try [this](https://github.com/JoshuaWise/better-sqlite3/issues/214#issuecomment-450114075).

**Comment by Rhino149** [comment]
/home/Rhino149/Tsuyo-master/modules/_functions.js:184
    client.logger.error(err.stack);
                  ^

TypeError: client.logger.error is not a function
    at process.<anonymous> (/home/Rhino149/Tsuyo-master/modules/_functions.js:184:19)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:165:25)

**Comment by Rhino149** [comment]
npm install better-sqlite3 also

**Comment by VenkSociety** [comment]
Apparently "fix" auto-closes an issue, my bad. But yeah, latest commit should fix this.

**Comment by Rhino149** [comment]
/home/Rhino149/Tsuyo-master/modules/_functions.js:159
        client.logger.error(err.stack)
                      ^

TypeError: client.logger.error is not a function
    at process.<anonymous> (/home/Rhino149/Tsuyo-master/modules/_functions.js:159:18)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:165:25)
still getting it

**Comment by Rhino149** [comment]
also if i do npm install again this happens 

> Tsuyo@1.0.0 install /home/Rhino149/Tsuyo-master
> node-gyp rebuild

make: Entering directory '/home/Rhino149/Tsuyo-master/build'
make: *** No rule to make target 'Release/obj.target/binding/src/binding.o', needed by 'Release/obj.target/binding.node'.  Stop.
make: Leaving directory '/home/Rhino149/Tsuyo-master/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/Rhino149/.config/nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.98-08076-g24ab33fb8e14
gyp ERR! command "/home/Rhino149/.config/nvm/versions/node/v14.2.0/bin/node" "/home/Rhino149/.config/nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Rhino149/Tsuyo-master
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Tsuyo@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Tsuyo@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by VenkSociety** [comment]
Hm... Tsuyo doesn't _fully_ support Linux yet if you're running on Linux. That error isn't really related to Tsuyo, it's more of a [node-gyp](https://github.com/nodejs/node-gyp) issue so I'd recommend trying that. 

I know that there was a similar error to this in the past which required something with `windows-build-tools`? Though I don't think this will help in your case.

As for the client.logger issue, what happens if you replace `client.logger.error(err.stack)` with `client.logger.error(err.stack);`? Note the semicolon.

**Comment by Rhino149** [comment]
it will be the same thing

**Comment by VenkSociety** [comment]
[This](https://stackoverflow.com/a/31013390) says otherwise.

**Comment by Rhino149** [comment]
yeah makes no difference

**Comment by Rhino149** [comment]
welp atleast most of the commands work with this persons [commands](https://github.com/AnIdiotsGuide)
